x-veld:
  code:

services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src:/veld/code/
    working_dir: /veld/code/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password=''

