x-veld:
  executable:

services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password=''

  # helper service, to transform notebook into py script for non-interactive execution
  convert_notebook:
    build: .
    volumes:
      - ./src:/veld/executable/
    command: jupyter nbconvert --to script /veld/executable/train.ipynb
