x-veld:
  code:
    about:
      description: "a fasttext training and inference jupyter notebook."
      topics:
        - "NLP"
        - "Machine Learning"
        - "word embeddings"

    inputs:
      volume: /veld/input/
      file_formats: "txt"
      contents: "natural text"
      description: "training data must be expressed as one sentence per line."

    outputs:
      volume: /veld/output/
      file_formats: "fasttext model"
      contents: "word embeddings"

    environment:
      in_train_data_file:
        file_type: "txt"
        volume: /veld/input/
      out_model_file:
        file_type: "bin"
        volume: /veld/output/
      vector_size:
        var_type: int
        default: 200
        description: "hyperparameter: the dimension of the vectors to be trained."
      epochs:
        var_type: int
        default: 50
        description: "hyperparameter: the number of epochs of the training."


services:
  veld_train:
    build: .
    command: python /veld/code/train.py
    volumes:
      - ./src/train/train.py:/veld/code/train.py:z
    environment:
      in_train_data_file: null
      out_model_file: null
      vector_size: 200
      epochs: 50

