x-veld:
  code:
    about:
      description: "a fasttext training and inference jupyter notebook."
      topics:
        - "NLP"
        - "Machine Learning"
        - "word embeddings"

    inputs:
      volume: /veld/input/
      file_formats: "txt"
      contents: "natural text"
      description: "training data must be expressed as one sentence per line."

    outputs:
      - volume: /veld/output/1/
        file_formats: "fasttext model"
        contents: "word embeddings"
      - volume: /veld/output/2/
        file_formats: "yaml"
        contents: "model metadata"

    environment:
      in_train_data_path:
        type: file
        volume: /veld/input/
      out_model_path:
        type: folder
        volume: /veld/output/1/
      out_metadata_path:
        type: file
        volume: /veld/output/2/
      train_data_description:
        type: str
        description: "a human label or a precise identifier for the training data set used"
      training_architecture:
        type: str
        description: "a human label for the kind of fasttext architecture, or version of it"
      vector_size:
        type: int
        default: 200
        description: "hyperparameter: the dimension of the vectors to be trained."
      epochs:
        type: int
        default: 50
        description: "hyperparameter: the number of epochs of the training."



services:
  veld:
    build: .
    command: python train.py
    working_dir: /veld/code/
    ports:
      - 8888:8888
    volumes:
      - ./src:/veld/code/
    environment:
      in_train_data_path: null
      out_model_path: null
      out_metadata_path: null
      train_data_description: null
      training_architecture: null
      vector_size: 200
      epochs: 50

